#!/usr/bin/env python
#
# Copyright (C) 2006-2018  CZ.NIC, z. s. p. o.
#
# This file is part of FRED.
#
# FRED is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FRED is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FRED.  If not, see <https://www.gnu.org/licenses/>.

"""
This is main script handling all functions of this client.
Here it's deside what type of application will be running.
Default is console. Next choice is running as a batch -
this is suitable using is in some shell scripts or for manage
web pages (php, html).

It use options from command line parsed
in module fred.translate during import.

MODES:
For console mode is used module fred.console.
For batch mode is used modules fred.creator and fred.sender.
"""
import sys, os

old_cwd = os.getcwd()
try:
    os.chdir(os.path.dirname(sys.argv[0]))
except OSError:
    pass

# setup.py will change this path to reflect changes in prefix
# and/or root option during install
sys.path.insert(0, '.')

import fred
import fred.console

if __name__ == '__main__':
    fred.console.main()
    os.chdir(old_cwd)
