__all__ = [
        'config.py',
        'build.py',
        'build_py.py',
        'buidl_scripts.py',
        'install.py',
        'install_data.py',
        'install_scripts.py',
        'sdist.py',
        'bdist.py',
        'bdist_rpm.py',
        'clean.py',
        'uninstall.py',
        'install_lib.py',
        ]
